spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillforge
    username: postgres
    password: 2006kruthi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: SkillForge

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwt:
    secret: "your-secret-key-change-this-in-production-at-least-32-characters-long"
    expiration: 86400000
